package game_detail

var GameName = map[string]string{
	"Soccer":                     "足球",
	"BasketBall":                 "篮球",
	"Football":                   "美式足球",
	"Tennis":                     "网球",
	"Baseball":                   "棒球",
	"Ice Hockey":                 "冰上曲棍球",
	"Specials":                   "特別投注",
	"Handball":                   "手球",
	"Rugby League":               "橄榄球联盟",
	"Golf":                       "高尔夫球",
	"Snooker & Pool":             "斯诺克 / 台球",
	"Motor Racing":               "赛车",
	"Darts":                      "飞镖",
	"Cycling":                    "自行车",
	"Poker":                      "扑克",
	"Speedway":                   "沙地摩托车",
	"Volleyball":                 "排球",
	"Boxing":                     "拳击",
	"Athletics":                  "田径",
	"Cricket":                    "板球",
	"Hockey":                     "曲棍球",
	"Floorball":                  "地板球",
	"Futsal ":                    "室内五人制足球",
	"Table Tennis":               "乒乓球",
	"Bowls ":                     "草地滚球",
	"Winter sports":              "冬季运动",
	"Hurling":                    "板棍球",
	"Sailing":                    "帆船",
	"Water Polo":                 "水球",
	"Beach Volleyball":           "沙滩排球",
	"Beach Soccer":               "沙滩足球",
	"Badminton":                  "羽毛球",
	"Rugby Union":                "橄榄球联合会",
	"Trotting":                   "马车赛",
	"Curling":                    "冰壶",
	"Olympic Games":              "奥运",
	"Bandy":                      "班迪球",
	"Beach Handball":             "沙滩手球",
	"Aussie Rules":               "澳式橄榄球",
	"Winter Olympic":             "冬季奥运会",
	"MMA":                        "综合格斗",
	"Shooting":                   "射击",
	"Swimming":                   "游泳",
	"Gymnastics":                 "体操",
	"Rowing":                     "划船",
	"Triathlon":                  "铁人三项",
	"Kayak":                      "皮艇",
	"Judo":                       "柔道",
	"Wrestling":                  "摔角",
	"Archery":                    "射箭",
	"Diving":                     "潜水",
	"Equestrian":                 "马术",
	"Fencing":                    "击剑",
	"Modern Penthathlon":         "现代五项",
	"Taekwondo":                  "跆拳道",
	"Weightlifting":              "举重",
	"Surfing":                    "冲浪运动",
	"Horse Racing":               "赛马",
	"Virtual Sports 虚拟体育Netball": "篮网球",
	"e-Sports":                   "电子竞技",
	"Chess":                      "国际象棋",
	"Greyhounds":                 "赛狗",
	"Gaelic Football":            "爱尔兰盖尔橄榄球",
	"Gaelic Hurling":             "爱尔兰盖尔曲棍球",
	"Virtual Sports 3Way":        "虚拟足球",
	"Virtual Sports 2Way":        "虚拟篮球",
}

var EventTypeName = map[string]string{
	//"Exact Score 1st Half":"上半场正确比分",
	//"Halftime/Fulltime":"半场/全场",
	//"Exact Score":"正确比分",
	//"MoneyLine":"独赢盘",
	//"LineType1":"线1",
	//"Winner":"获胜者",
	"Over":     "大于",
	"Under":    "小于",
	"1X2":      "1x2",
	"Asians":   "亚洲",
	"Handicap": "让分盘",
	//"Exact Score":"正确比分",
	//"Halftime/Fulltime":"半场/全场",
	//"Spread":"让分盘",
	//"Exact Score 1st Half":"上半场正确比分",
	"Asian Handicap": "亚洲让分盘",
	//"O/U":"大/小",
	"Exact Score 1st Half": "上半场正确比分",
	"OU":                   "大小",
	//"Halftime/Fulltime":"半场/全场",
	"Exact Score": "正确比分",
	//"Winner":"获胜者",
	//"Relegation":"驱逐离场",
	//"Odd/Even
	"First Player To Score first and Final Score": "单/双",
	"Double Chance":  "首个球员最先和最后得分",
	"First to Score": "双重机会",
	"To Win To Nil":  "首先进球",
	//"Penalty":"无失球胜出",
	"Team To Score First & Win / Draw / Loose": "罚球",
	"First Method Of Scoring":                  "首先得分队伍 & 胜/平/输",
	//"30 Sec Pulse":"第一个进球得分方法",
	"Player Props":                       "30秒脉博",
	"Home":                               "球员竞猜",
	"OwnGoal":                            "主队",
	"To Score A Penalty":                 "乌龙球",
	"To Win From Behind":                 "罚球得分",
	"Half With Most Goals":               "落后反超",
	"Both To Score No Draw":              "最多进球数的半场",
	"Both Teams To Score In Both Halves": "两队皆得分且非平手",
	//"5 Min Pulse":"上下半场两队皆得分",
	"Second Method Of Scoring":                "5分钟脉博",
	"Score First Or Last":                     "第二个进球得分方法",
	"Number Of Goals 1st Half":                "先得分或最后",
	"Team To Score First & Win / Draw / Lose": "上半场进球数",
	"To Win Either Half":                      "首先得分队伍 & 胜/平/输",
	"Both to Score":                           "赢得其中一个半场",
	"To Miss A Penalty":                       "两队皆得分",
	//"Not Implemented":"罚点球失误",
	"Winning Margin": "并未执行",
	//"10 Min Pulse":"净胜比分",
	//"1 Min Pulse":"10分钟脉博",
	"LineType1": "1分钟脉博",
	"Yes":       "线1",
	//"10 Min Pulse":"是",
	"Away": "10分钟脉博",
	//"1 Min Pulse":"客队",
	"LineType2":       "1分钟脉博",
	"Last to Score":   "线2",
	"Score 2 or More": "最后进球",
	//"5 Min Pulse":"得到2分或以上",
	//"30 Sec Pulse":"5分钟脉博",
	//"5 Min Pulse":"30秒脉博",
	"LineType3":              "5分钟脉博",
	"1st Goalscorer":         "线3",
	"Score 3 or More":        "首先进球球员",
	"Anytime Scorer":         "得到3分或以上",
	"10 Min Pulse":           "任意时间得分球员",
	"1 Min Pulse":            "10分钟脉博",
	"30 Sec Pulse":           "1分钟脉博",
	"Double Chance 1st Half": "30秒脉博",
	"Goals":                  "上半场双重机会",
	"Corners":                "进球",
	"Penalty":                "角球",
	"Not Implemented":        "罚球",
	"Cards":                  "并未执行",
	"Free-Kick":              "罚牌",
	"Goal-Kick":              "任意球",
	"Throw-In":               "球门球",
	"None":                   "掷界外球",
	//"Winner":"无",
	"Moneyline":            "获胜者",
	"Spread":               "独赢盘",
	"O/U":                  "让分盘",
	"Winner":               "大/小",
	"Relegation":           "获胜者",
	"Odd/Even":             "驱逐离场",
	"2nd Quarter Odd/Even": "单/双",
	"Highest Half":         "第二节单/双",
	//"Halftime/Fulltime":"最多进球数的半场",
	"1st Scoring Play":        "半场/全场",
	"1st Half Odd/Even":       "第一场得分比赛",
	"Highest Scoring Quarter": "上半场单/双",
	"Total Odd/Even":          "最高得分节",
	"1st Quarter Odd/Even":    "最高得分节",
	//"LineType1":"总得分单/双",
	"Over Time": "第一节单/双",
	//"LineType2":"线1",
	//"Halftime/Fulltime":"超时",
	//"Halftime/Fulltime":"线2",

}
